### ISSUE TITLE
Automatic evaluation disabled for linked cells

### ISSUE THREAD

**Issue by paulmasson** [sagemath/sagecell#473]
When cells are linked, automatic evaluation is [disabled](https://github.com/sagemath/sagecell/blob/master/js/cell.js#L80). This can be worked around by clicking the evaluation buttons with JavaScript, but it would be nice not to have to do this.

Automatic evaluation is presumably disabled for linked cells because the order in which they are evaluated is important. This can be inferred from the position of the cells in the DOM using `compareDocumentPosition()`, although it may be problematic in older browsers.

Additionally, if the evaluation buttons are clicked all at the same time the server currently returns the output of all linked cells in a single location. This is presumably a timing issue of some sort, since it can be avoided by delaying the click for cells dependent on previous cells.

**Comment by novoselt** [comment]
I was told that this is done in order to decrease the load on servers. I am fine dropping this extra complication for settings (I mean - autoevaluation and linking are kind of independent logically).

"Clicked at the same time" never happens with a human user ;-) But presumably similar issue may appear with fast clicking and slow network or long computation, so would be nice to figure out what exactly is going on and fix it.
