### ISSUE TITLE
Detect the end of a calculation

### ISSUE THREAD

**Issue by ro70** [sagemath/sagecell#544]
Is it possible to detect the end of a calculation in order to continue using the output immediately afterwards?

**Comment by novoselt** [comment]
You probably want to look at https://jupyter-client.readthedocs.io/en/latest/messaging.html#messaging and see to what extend they are exposed. There is also change of the border colour and spinning wheel when computation is done: https://github.com/sagemath/sagecell/blob/d17abad8b3a080895e66daaf8af0ec5736d2388c/js/session.js#L258 I would also suggest using sage-cell mailing list for such questions instead of issues ;-)
