### ISSUE TITLE
Retire IE Support?

### ISSUE THREAD

**Issue by siefkenj** [sagemath/sagecell#549]
I am wondering how much priority IE support has. Microsoft is ending support for IE on June 15, 2022. If Sagecell is willing to drop support, some code could be removed.

**Comment by novoselt** [comment]
Is there a strong reason to drop it now rather than later? I certainly see no point in supporting it past Microsoft deadline, but it makes sense to maintain it until then.

**Comment by siefkenj** [comment]
June is pretty close, but it means that things like the `async` keyword cannot be used or would need cross-compilation. Cross-compilation might be the way to go, but I hear it just about doubles file sizes...

Is sagecell versioned? One could keep a copy of the old sagecell hosted as `sagecell_legacy` for those who need it.

**Comment by novoselt** [comment]
No versions - the current master is generally expected to work with the current SageMath master (which is not quite the case in the moment - interacts are broken with Sage 9.5). I am not going to maintain multiple brunches, I am actually not aware of people currently running their own servers instead of the public ones. I used to do it before taking over the maintenance of the public servers, now their changes don't surprise me ever ;-)

Is Edge available on all platforms where IE runs? If apart from removing old code new code can be written in a better way, I am OK with dropping its support.

**Comment by novoselt** [comment]
A reliable Internet source claims for 2022 about IE "On traditional PCs, the only platform on which it has ever had significant share, it is ranked 6th at 1.06%"

**Comment by siefkenj** [comment]
Edge is available on all supported platforms that IE runs.

**Comment by novoselt** [comment]
OK, feel free to get rid of it!
